## numpy :
---------
-  The main intetion of NumPy module to provide Multi dimentional array object and tools for working with these arrays.
-  NumPy is core library or module for scientific Arrays computing in Python.
-  NumPy contains N-Dimensional arrays and tools for integrating with C and C++
-  NumPy is used for linear Alzeebra with random numbers capabilities.
-  NumPy can be used for Multi Dimensaionl Container for generic data.

## Array:
----------
- It is a data structure, it able to allow group of elements of same data type.
- IN general, two types of arrays.
    1. Single Dimensional Arrays
    2. Multi Dimensional Arrays.

### 1. Single Dimensional Array: It is an array ,it contains only one Row.
        EX:
         0 1 2 3 4
        0 [1,2,3,4,5]
        
         A[0,0] = 1
         A[0,1] = 2
         A[0,2] = 3
         A[0,3] = 4
         A[0,4] = 5


### 2. Multi Dimensional Array:It conatains data in more than one domension.
        EX:2 Dimensional Array
           0 1 2 3 4 
        0 [1,2,3,4,5]
        1 [2,3,4,5,6]
        2 [3,4,5,6,7]
        3 [4,5,6,7,8]
        
        A[0,3] = 4
        A[1,2] = 4
        A[3,3] = 7 
        A[2,4] = 8


- To Use Numpy in Python apllications, first, we have to import Numpy module to our python file.
            EX: import numpy as np
- To create an array by using numpy we will use a function array().

In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\python38\python.exe -m pip install --upgrade pip' command.


In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


- To create Multi dimentional arrays we have to use tuples as dimentions in list.


In [2]:
### :2-Dimensional Array

import numpy as np
a = np.array([(1,2,3,4),(2,3,4,5),(3,4,5,6),(4,5,6,7)])
print(a)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [3]:
###  3-Dimensional Array :
import numpy as np
a = np.array([[(1,2,3),(2,3,4)],[(2,3,4),(3,4,5)],[(3,4,5),(4,5,6)],
[(4,5,6),(5,6,7)]])
print(a)

[[[1 2 3]
  [2 3 4]]

 [[2 3 4]
  [3 4 5]]

 [[3 4 5]
  [4 5 6]]

 [[4 5 6]
  [5 6 7]]]


## Q)To provide array of elements we have already List, tuple,range,... then what is the requirement to use NumPy?
-  because of the following three reasons.
    1. Less Memory
    2. Faster
    3. Convenient


#### 1. Numpy will take "Less Memory" when compared with List, tuple, range,....

In [16]:
import numpy as np
import sys
a = range(100)
print("a                      ====>",a)
print('sys.getsizeof(a)*len(a)====>',sys.getsizeof(a)*len(a))
print('sys.getsizeof(a)       ====>',sys.getsizeof(a))
print('len(a)                  ===>',len(a))
print()
b = np.arange(100)
print('b                       ===>',b)
print('b.size*b.itemsize     =====>',b.size*b.itemsize)
print('b.size                  ===>',b.size)
print('len(b)                 ====>',len(b))
print('b.itemsize             ====>',b.itemsize)


a                      ====> range(0, 100)
sys.getsizeof(a)*len(a)====> 4800
sys.getsizeof(a)       ====> 48
len(a)                  ===> 100

b                       ===> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
b.size*b.itemsize     =====> 400
b.size                  ===> 100
len(b)                 ====> 100
b.itemsize             ====> 4


- Where "sys.getsizeof(a)" will return size of single element.
- Where "sys.getsizeof(a)*len(a)" will return all the elements size which are available in range.
- Where "b.itemsize" variable is able to return single item size.
- Where "b.size" will return the no of elements in range.
- Where "b.size*b.itemsize" will return the size of all the elements available in range.

#### 2. Numpy is more Faster than list, tuple, range,.....